name: Test Helpers

on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]

jobs:
  jq:
    runs-on: ubuntu-latest
    name: jq
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Test base
        uses: ./helpers/jq

      - name: Test with path
        uses: ./helpers/jq
        with:
          path: test_files

  vcn:
    runs-on: ubuntu-latest
    name: vcn
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Run action
        uses: ./helpers/vcn

      - name: Verify installation
        run: which vcn

  info:
    runs-on: ubuntu-latest
    name: info
    strategy:
      fail-fast: False
      matrix:
        file:
          - "build"
          - "config"
        type: 
          - "json"
          - "yaml"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Test
        uses: ./helpers/info
        id: info
        with:
          path: "test_files/${{ matrix.file }}_${{ matrix.type }}"

      - name: Validate result
        run: |
          if [[ '${{ steps.info.outputs.architectures }}' != '["aarch64","armv7","armhf","amd64","i386"]' ]]; then
            exit 1
          fi

  find-addons:
    runs-on: ubuntu-latest
    name: find-addons
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Test
        uses: ./helpers/find-addons
        id: addons

      - name: Validate result
        run: |
          if [[ '${{ steps.addons.outputs.addons }}' != '["aarch64","armv7","armhf","amd64","i386"]' ]]; then
            exit 1
          fi
