---
name: Stale

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_call:
    inputs:
      days-before-stale:
        description: "Idle number of days before marking issues/PRs stale"
        default: 30
        required: false
        type: number
      days-before-close:
        description: "Idle number of days before closing stale issues/PRs"
        default: 7
        required: false
        type: number

  workflow_dispatch:

jobs:
  stale:
    name: ðŸ§¹ Clean up stale issues and PRs
    runs-on: ubuntu-latest
    permissions:
      contents: write  # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - name: ðŸš€ Run stale
        uses: actions/stale@v8.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: ${{ inputs.days-before-stale }}
          days-before-close: ${{ inputs.days-before-close }}
          remove-stale-when-updated: true
          stale-issue-label: "stale"
          exempt-issue-labels: "pinned,no-stale,help-wanted,rfc,security"
          stale-issue-message: >
            There hasn't been any activity on this issue recently, so we
            clean up some of the older and inactive issues.

            Please make sure to update to the latest version and
            check if that solves the issue. Let us know if that works for you
            by leaving a comment ðŸ‘

            This issue has now been marked as stale and will be closed if no
            further activity occurs. Thank you for your contributions.
          stale-pr-label: "stale"
          exempt-pr-labels: "pinned,no-stale,rfc,security"
          stale-pr-message: >
            There hasn't been any activity on this pull request recently. This
            pull request has been automatically marked as stale because of that
            and will be closed if no further activity occurs within 7 days.

            Thank you for your contributions.
